language: java

script: mvn --file geozet-webapp/pom.xml clean test verify

jdk:
  - openjdk7
  - oraclejdk8

branches:
  except:
    - master

matrix:
  fast_finish: true
  allow_failures:
    # some tests fail due to different attribute ordering in string serialization
    - jdk: oraclejdk8
